dist: xenial
language: python
python:
  - "3.7"

install:
  - sudo apt update 
  - sudo apt install --only-upgrade sqlite3
  - pip3 install -r requirements.txt -U --user

script:
  - python3 manage.py runserver &
  - FLASK_APP=micro_user/main.py flask run --port 5000 &
  - FLASK_APP=micro_data/main.py flask run --port 5001
  - python3 manage.py test
  - pytest -v