language: python
python:
  - "3.6"

install:
  - pip3 install -U -r requirements.txt 

script:
  - python3 manage.py runserver &
  - FLASK_APP=micro_user/main.py flask run --port 5000 &
  - FLASK_APP=micro_data/main.py flask run --port 5001 &
  - python3 manage.py test
  - pytest -v