apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
  labels:
    app: web
    project: htwg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      namespace: default
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: web
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: 100m
        image: vladmasarik/htwg-web:latest
        ports:
        - containerPort: 8080
          name: http