apiVersion: v1
kind: Deployment
metadata:
  name: user
  namespace: default
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      namespace: default
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: vladmasarik/htwg-user
        env:
        - name: ETCDCTL_API
          value: "3"
        ports:
        - containerPort: 5000
          name: data