apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  namespace: default
  labels:
    app: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      namespace: default
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: vladmasarik/htwg-data
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-web
              key: aws-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-web
              key: aws-pass
        ports:
        - containerPort: 5000
          name: data