apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: default
  labels:
    app: user
    project: htwg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      namespace: default
      labels:
        app: user
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: user
        image: vladmasarik/htwg-user:latest
        imagePullPolicy: "Always"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-web
              key: aws-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-web
              key: aws-pass
        - name: AWS_DEFAULT_REGION
          value: "us-west-2"
        ports:
        - containerPort: 5000
          name: data